# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85265f0d1955c69f5b1dba37c218ef5290f0906c42865e4777e8d42a8d5cea32c8b3494f4eedd699f604c9fd611c25771bce1e83e68fad78f246e889eca9cd1b

test:
  secret_key_base: 8054a19b5b9b9d93b2b3ff970ac1a655c7207f4961212f76593ad9cc1c8f6015ed4e35ff1ceb99a087648d15c71a190048ee46f691e9485507d0414c99489fe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
